# Generated by Django 6.1.1 on 2026-10-02 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DentFlow Klinikasi', max_length=200, verbose_name='Klinika nomi')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Bot Token')),
                ('work_start', models.TimeField(default='09:00', verbose_name='Ish vaqti boshlanishi')),
                ('work_end', models.TimeField(default='18:00', verbose_name='Ish vaqti tugashi')),
                ('reminder_24h', models.BooleanField(default=True, verbose_name='24 soat eslatma')),
                ('reminder_1h', models.BooleanField(default=True, verbose_name='1 soat eslatma')),
                ('reminder_24h_template', models.TextField(default='🦷 Eslatma!\n\nErtaga {date} soat {time} da {doctor} dr. qabuli bor.\n\nKlinika: {clinic_name}\nManzil: {address}', verbose_name='Shablон (24h)')),
                ('reminder_1h_template', models.TextField(default="⏰ 1 soatdan so'ng {time} da {doctor} dr. qabuli bor.\n\nKlinika: {clinic_name}\nManzil: {address}", verbose_name='Shablon (1h)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Klinika sozlamalari',
                'verbose_name_plural': 'Klinika sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('speciality', models.CharField(default='Stomatolog', max_length=200, verbose_name='Mutaxassislik')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Rasm')),
                ('slot_duration', models.PositiveIntegerField(default=30, verbose_name='Qabul davomiyligi (daqiqa)')),
                ('work_start', models.TimeField(default='09:00', verbose_name='Ish boshlanishi')),
                ('work_end', models.TimeField(default='18:00', verbose_name='Ish tugashi')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Tanaffus boshlanishi')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Tanaffus tugashi')),
                ('work_days', models.JSONField(default=list, verbose_name='Ish kunlari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Eslatmalar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'ylxatga olingan")),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(default='🦷', max_length=10, verbose_name='Ikonka (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy boshlanish')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy tugash')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugagan'), ('cancelled', 'Bekor qilingan'), ('rescheduled', "Ko'chirilgan"), ('no_show', 'Kelmadi')], default='pending', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Narx')),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24h', '24 soat oldin'), ('1h', '1 soat oldin'), ('delay', 'Kechikish xabari'), ('cancelled', 'Bekor qilish xabari')], max_length=20, verbose_name='Tur')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuborilgan vaqt')),
                ('is_success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clinic.appointment')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.ManyToManyField(blank=True, related_name='services', to='clinic.doctor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='clinic.servicecategory')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.service'),
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Dam olish kuni',
                'verbose_name_plural': 'Dam olish kunlari',
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
